import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import MyThemeProvider from "@/providers/theme";
import { bgModel } from "@/config";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions, getServerAuthSession } from "@/server/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "Icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={`font-sans ${inter.variable}`}>
          <MyThemeProvider>
            <TRPCReactProvider>
              <Toaster richColors position={"top-right"} />

              <div className={"relative h-screen w-screen"}>
                <div
                  className={cn(
                    "fixed inset-0 z-0 h-full w-full",
                    "pointer-events-none",
                    bgModel === "mirror"
                      ? "scale-125 blur-lg brightness-[15%]"
                      : "bg-background",
                  )}
                >
                  {bgModel === "plain" ? null : children}
                </div>

                <div
                  className={
                    "absolute inset-0 flex h-full w-full justify-center"
                  }
                >
                  <div className={"bg-muted w-full max-w-screen-sm"}>
                    {children}
                  </div>
                </div>
              </div>
            </TRPCReactProvider>
          </MyThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
