import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/lib/utils";
import MyThemeProvider from "@/providers/theme";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "Icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans ${inter.variable}`}>
        <MyThemeProvider>
          <TRPCReactProvider>
            <div className={"relative h-screen w-screen"}>
              <div
                className={cn(
                  "fixed inset-0 z-0 h-full w-full scale-125 blur-lg brightness-[15%]",
                  "pointer-events-none",
                )}
              >
                {children}
              </div>

              <div
                className={"absolute inset-0 flex h-full w-full justify-center"}
              >
                <div className={"w-full max-w-screen-sm"}>{children}</div>
              </div>
            </div>
          </TRPCReactProvider>
        </MyThemeProvider>
      </body>
    </html>
  );
}
