import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import MyThemeProvider from "@/providers/theme";
import { bgModel } from "@/config";
import { Toaster } from "sonner";
import MySessionProvider from "@/providers/session";
import { TRPCReactProvider } from "@/providers/trpc";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "Icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`font-sans ${inter.variable}`}>
        <MyThemeProvider>
          <MySessionProvider>
            <TRPCReactProvider>
              <Toaster richColors position={"top-right"} />

              <div className={"relative h-screen w-screen"}>
                <div
                  className={cn(
                    "fixed inset-0 z-0 h-full w-full",
                    "pointer-events-none",
                    bgModel === "mirror"
                      ? "scale-125 blur-lg brightness-[15%]"
                      : "bg-background",
                  )}
                >
                  {bgModel === "plain" ? null : children}
                </div>

                <div
                  className={
                    "absolute inset-0 flex h-full w-full justify-center"
                  }
                >
                  <div className={"bg-muted w-full max-w-screen-sm"}>
                    {children}
                  </div>
                </div>
              </div>
            </TRPCReactProvider>
          </MySessionProvider>
        </MyThemeProvider>
      </body>
    </html>
  );
}
